name: Terraform Destroy

# on:
#   workflow_run:
#     workflows: ["Deploy"]
#     types:
#       - completed
on:
  push:
    branches:
      - destroyer

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Destroy Infrastructure
        run: terraform destroy -auto-approve
