name: Terraform Deploy and Destroy

on:
  push:
    branches:
      - main  

#run on the latest version of Ubuntu.
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./terraform

    #the code for the workflow from my repo.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          #terraform_version: 0.14.7
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup Terraform Backend
        id: backend
        run: |
            cat > backend.tf << EOF
            terraform { 
            cloud {
                organization = "${{ secrets.TF_CLOUD_ORGANIZATION }}"
                workspaces {
                name = "${{ secrets.TF_CLOUD_WORKSPACE_OWAWS }}"
                }
            }
            }
            EOF
      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan #-var="instance_type=${{ secrets.TF_VAR_INSTANCE_TYPE }}" -var="ami=${{ secrets.TF_VAR_AMI }}"
      
      - name: Deploy Infrastructure
        run: terraform apply -auto-approve
        
        




